export const ANALYTICS_EVENTS = {
  PAGE_VIEW: 'page_view',
  SIGN_UP_SUCCESS: 'sign_up_success',
  FIRST_EXPERIENCE_CREATED: 'first_experience_created',
  RESUME_EXPORTED: 'resume_exported',
  RESUME_CARD_CHECKED: 'resume_card_checked',
  EXPERIENCE_BANK_IMPORTED: 'experience_bank_imported',
  EXPERIENCE_BANK_EXPORTED: 'experience_bank_exported',
  AI_POLISH_START: 'ai_polish_start',
  AI_POLISH_RESULT: 'ai_polish_result',
  JD_ANALYSIS_START: 'jd_analysis_start',
  JD_ANALYSIS_COMPLETE: 'jd_analysis_complete',
  LAYOUT_MODE_CHANGE: 'layout_mode_change',
  SMART_ONE_PAGE_TRIGGERED: 'smart_one_page_triggered',
  MODULE_REORDERED: 'module_reordered',
} as const;

export const ANALYTICS_PROPERTIES = {
  VIEW: 'view',
  PATH: 'path',
  CATEGORY: 'category',
  SOURCE: 'source',
  FIELD: 'field',
  ACTION: 'action',
  DURATION_MS: 'duration_ms',
  MATCH_SCORE: 'match_score',
  FROM: 'from',
  TO: 'to',
  LINE_HEIGHT: 'line_height',
  FONT_SIZE: 'font_size',
  MODULE_TYPE: 'module_type',
  MODULE_KEY: 'module_key',
  SECTION_ID: 'section_id',
  RESUME_ID: 'resume_id',
  FROM_POSITION: 'from_position',
  TO_POSITION: 'to_position',
  EXPORT_COUNT_BEFORE: 'export_count_before',
  AI_ANALYSIS_COUNT: 'ai_analysis_count',
  RESUME_SORT_COUNT: 'resume_sort_count',
  CARD_TYPE: 'card_type',
  CHECKED: 'checked',
  EXPERIENCE_COUNT: 'experience_count',
  CERTIFICATION_COUNT: 'certification_count',
  SKILL_COUNT: 'skill_count',
  PERSONAL_INFO_COUNT: 'personal_info_count',
  TOTAL_SELECTED: 'total_selected',
  WORK_COUNT: 'work_count',
  PROJECT_COUNT: 'project_count',
  EDUCATION_COUNT: 'education_count',
} as const;

export type AiPolishAction = 'applied' | 'edited' | 'discarded';
