FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_LOGTO_ENDPOINT
ARG VITE_LOGTO_APP_ID
ARG VITE_LOGTO_REDIRECT_URI
ARG VITE_LOGTO_ACCOUNT_CENTER_URL
ARG VITE_UMAMI_HOST
ARG VITE_UMAMI_WEBSITE_ID

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_LOGTO_ENDPOINT=$VITE_LOGTO_ENDPOINT \
    VITE_LOGTO_APP_ID=$VITE_LOGTO_APP_ID \
    VITE_LOGTO_REDIRECT_URI=$VITE_LOGTO_REDIRECT_URI \
    VITE_LOGTO_ACCOUNT_CENTER_URL=$VITE_LOGTO_ACCOUNT_CENTER_URL \
    VITE_UMAMI_HOST=$VITE_UMAMI_HOST \
    VITE_UMAMI_WEBSITE_ID=$VITE_UMAMI_WEBSITE_ID

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN test -n "$VITE_API_BASE_URL" \
    && test -n "$VITE_LOGTO_ENDPOINT" \
    && test -n "$VITE_LOGTO_APP_ID" \
    && test -n "$VITE_LOGTO_REDIRECT_URI" \
    && test -n "$VITE_LOGTO_ACCOUNT_CENTER_URL" \
    && test -n "$VITE_UMAMI_HOST" \
    && test -n "$VITE_UMAMI_WEBSITE_ID" \
    && npm run build

FROM nginx:1.27-alpine

ARG BACKEND_UPSTREAM=resumeflow-botism.zeabur.internal:8000

ENV BACKEND_UPSTREAM=$BACKEND_UPSTREAM \
    NGINX_ENVSUBST_FILTER=BACKEND_UPSTREAM

COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
