import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

test('assistant supports editor sidebar surface and full-page session handoff', () => {
  const assistant = read('views/AIAssistant.tsx');
  const conversationViewport = read('views/AIAssistant/AssistantConversationViewport.tsx');
  const sidebarHeader = read('views/AIAssistant/AssistantSidebarHeader.tsx');
  const sidebarDropdown = read('views/AIAssistant/AssistantSidebarHistoryDropdown.tsx');
  const chatInput = read('views/AIAssistant/ChatInputBox.tsx');
  const types = read('views/AIAssistant/types.ts');
  const draftPanel = read('views/AIAssistant/AssistantDraftPanel.tsx');
  const draftState = read('views/AIAssistant/useAssistantDraftPanelState.ts');
  const app = read('App.tsx');
  const editor = read('views/ResumeEditor/index.tsx');
  const conversationBlockStart = assistant.indexOf('<AssistantConversationViewport');
  const conversationBlock = assistant.slice(
    conversationBlockStart,
    assistant.indexOf('/>', conversationBlockStart) + 2,
  );

  assert.match(types, /export type AssistantOpenSessionRequest/);
  assert.match(app, /assistantOpenSessionRequest/);
  assert.match(app, /handleOpenAssistantSession/);
  assert.match(app, /pendingOpenSessionRequest=\{assistantOpenSessionRequest\}/);
  assert.match(app, /onConsumeOpenSessionRequest=\{handleConsumeAssistantOpenSessionRequest\}/);
  assert.match(editor, /onOpenAssistantSession\?: \(sessionId: string\) => void/);
  assert.match(editor, /onExpandToFullPage=\{handleExpandAssistantSidebar\}/);
  assert.match(editor, /const assistantSidebarSelectedResume = useMemo/);
  assert.match(editor, /snapshot: selectedResumeSnapshot/);
  assert.match(editor, /liveSelectedResume=\{assistantSidebarSelectedResume\}/);

  assert.match(assistant, /surface\?: 'full' \| 'sidebar'/);
  assert.match(assistant, /liveSelectedResume\?: AssistantSelectedResume \| null/);
  assert.match(assistant, /onOpenAnalysisDetails\?: \(\) => void/);
  assert.match(assistant, /const isSidebarSurface = surface === 'sidebar'/);
  assert.match(assistant, /normalizeSelectedResume\(liveSelectedResume\)/);
  assert.match(assistant, /!isSidebarSurface \|\| !isAuthenticated \|\| selectedSessionId/);
  assert.match(assistant, /prefillResume: implicitLiveSelectedResume \?\? undefined/);
  assert.match(assistant, /pendingOpenSessionRequest/);
  assert.match(assistant, /suppressAutoSelectSessionRef\.current = true/);
  assert.match(assistant, /setSelectedSessionId\(sessionId\)/);
  assert.match(assistant, /loadSessionDetail\(sessionId\)/);
  assert.match(assistant, /!isSidebarSurface \? \(\s*<AssistantHistoryPanel/);
  assert.match(assistant, /import \{ AssistantConversationViewport \} from '\.\/AIAssistant\/AssistantConversationViewport'/);
  assert.match(assistant, /<AssistantConversationViewport/);
  assert.match(assistant, /messageViewportRef=\{messageViewportRef\}/);
  assert.match(assistant, /composerReservedHeight=\{composerReservedHeight\}/);
  assert.match(assistant, /shouldShowEmptyAssistantGreeting=\{shouldShowEmptyAssistantGreeting\}/);
  assert.match(assistant, /isSending=\{isSending\}/);
  assert.doesNotMatch(conversationBlock, /onSelectSkillFollowup=\{handleSelectSkillFollowup\}/);
  assert.doesNotMatch(assistant, /messages\.map\(\(message\) =>/);
  assert.doesNotMatch(assistant, /readMessageAttachmentPreviews\(message\)/);
  assert.match(conversationViewport, /export const AssistantConversationViewport: React\.FC<AssistantConversationViewportProps>/);
  assert.match(conversationViewport, /ref=\{messageViewportRef\}/);
  assert.match(conversationViewport, /style=\{\{ paddingBottom: `\$\{composerReservedHeight\}px` \}\}/);
  assert.match(conversationViewport, /messages\.map\(\(message\) =>/);
  assert.match(conversationViewport, /message\.message_type === 'draft_card'/);
  assert.match(conversationViewport, /readMessageAttachmentPreviews\(message\)/);
  assert.match(conversationViewport, /readMessageSelectedExperiences\(message\)/);
  assert.match(conversationViewport, /readMessageSelectedResume\(message\)/);
  assert.match(conversationViewport, /<ActiveThoughtBlock thought=\{activeThought\} \/>/);
  assert.match(conversationViewport, /isSending: boolean/);
  assert.match(conversationViewport, /正在生成回复\.\.\./);
  assert.doesNotMatch(conversationViewport, /latestSuggestedFollowups\.map/);
  assert.doesNotMatch(assistant, /你的AI求职助手/);
  assert.doesNotMatch(assistant, /<Bot className="h-5 w-5" \/>/);
  assert.match(assistant, /const assistantSidebarTitle = selectedSession\?\.title\?\.trim\(\) \|\| 'AI助手';/);
  assert.match(assistant, /import \{ AssistantSidebarHeader \} from '\.\/AIAssistant\/AssistantSidebarHeader'/);
  assert.match(assistant, /<AssistantSidebarHeader/);
  assert.match(assistant, /title=\{assistantSidebarTitle\}/);
  assert.match(assistant, /isHistoryOpen=\{isSidebarHistoryOpen\}/);
  assert.match(assistant, /onNewChat=\{handleSidebarNewChat\}/);
  assert.match(assistant, /onToggleHistory=\{\(\) => setIsSidebarHistoryOpen\(\(current\) => !current\)\}/);
  assert.match(assistant, /onExpandToFullPage=\{\(\) => onExpandToFullPage\?\.\(selectedSessionId\)\}/);
  assert.match(assistant, /onOpenAnalysisDetails=\{onOpenAnalysisDetails\}/);
  assert.doesNotMatch(assistant, /pointer-events-none absolute right-3 top-3 z-20 flex items-center gap-1/);
  assert.doesNotMatch(assistant, /const SIDEBAR_ANALYSIS_BUTTON_CLASS/);
  assert.doesNotMatch(assistant, /<FileSearch className="h-4 w-4" \/>/);
  assert.match(sidebarHeader, /export const AssistantSidebarHeader: React\.FC<AssistantSidebarHeaderProps>/);
  assert.match(sidebarHeader, /MessageSquarePlus/);
  assert.match(sidebarHeader, /onNewChat\?: \(\) => void/);
  assert.match(sidebarHeader, /shrink-0 border-b border-slate-200\/90 bg-white\/95 px-4 py-3 backdrop-blur/);
  assert.match(sidebarHeader, /title=\{title\}/);
  assert.match(sidebarHeader, /pointer-events-auto inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-500 transition hover:text-slate-900 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400\/50 dark:text-slate-400 dark:hover:text-white/);
  const newChatButtonIndex = sidebarHeader.indexOf('onClick={onNewChat}');
  const analysisButtonIndex = sidebarHeader.indexOf('onClick={onOpenAnalysisDetails}');
  const historyButtonIndex = sidebarHeader.indexOf('onClick={onToggleHistory}');
  assert.ok(newChatButtonIndex >= 0, 'new chat button should be rendered');
  assert.ok(analysisButtonIndex >= 0, 'analysis details button should be rendered');
  assert.ok(historyButtonIndex >= 0, 'history button should be rendered');
  const newChatButtonBlock = sidebarHeader.slice(newChatButtonIndex, sidebarHeader.indexOf('</button>', newChatButtonIndex));
  assert.match(sidebarHeader, /onNewChat \? \(/);
  assert.match(sidebarHeader, /onClick=\{onNewChat\}/);
  assert.match(newChatButtonBlock, /className=\{SIDEBAR_ACTION_BUTTON_CLASS\}/);
  assert.match(sidebarHeader, /title="新建对话"/);
  assert.match(sidebarHeader, /aria-label="新建对话"/);
  assert.match(sidebarHeader, /<MessageSquarePlus className="h-4 w-4" \/>/);
  assert.doesNotMatch(newChatButtonBlock, /SIDEBAR_ANALYSIS_BUTTON_CLASS/);
  assert.match(sidebarHeader, /const SIDEBAR_ANALYSIS_BUTTON_CLASS = '[^']*text-emerald-600[^']*hover:text-emerald-700/);
  assert.doesNotMatch(sidebarHeader, /const SIDEBAR_ANALYSIS_BUTTON_CLASS = '[^']*\bbg-emerald-/);
  assert.doesNotMatch(sidebarHeader, /const SIDEBAR_ANALYSIS_BUTTON_STYLE/);
  assert.match(sidebarHeader, /onOpenAnalysisDetails \? \(/);
  assert.match(sidebarHeader, /onClick=\{onOpenAnalysisDetails\}/);
  assert.match(sidebarHeader, /className=\{SIDEBAR_ANALYSIS_BUTTON_CLASS\}[\s\S]*aria-label="查看分析详情"/);
  assert.doesNotMatch(sidebarHeader, /style=\{SIDEBAR_ANALYSIS_BUTTON_STYLE\}/);
  assert.match(sidebarHeader, /aria-label="查看分析详情"/);
  assert.match(sidebarHeader, /aria-controls="assistant-sidebar-history-panel"/);
  assert.match(sidebarHeader, /aria-expanded=\{isHistoryOpen\}/);
  assert.match(sidebarHeader, /aria-label=\{isHistoryOpen \? '关闭对话记录' : '打开对话记录'\}/);
  assert.match(sidebarHeader, /<History className="h-4 w-4" \/>/);
  assert.match(sidebarHeader, /<FileSearch className="h-4 w-4" \/>/);
  assert.match(sidebarHeader, /<Maximize2 className="h-4 w-4" \/>/);
  assert.ok(
    analysisButtonIndex < historyButtonIndex,
    'analysis details button should appear before history button in the sidebar header'
  );
  assert.ok(
    historyButtonIndex < newChatButtonIndex,
    'new chat button should appear to the right of history in the sidebar header'
  );
  assert.doesNotMatch(assistant, /bg-slate-100 text-slate-600 transition hover:bg-slate-200/);
  assert.match(assistant, /const \[isSidebarHistoryOpen, setIsSidebarHistoryOpen\] = useState\(false\)/);
  assert.match(assistant, /const handleSidebarNewChat = useCallback/);
  assert.match(assistant, /const handleSidebarSelectSession = useCallback/);
  assert.match(assistant, /setIsSidebarHistoryOpen\(false\);[\s\S]*void handleNewChat\('general'\)/);
  assert.match(assistant, /setIsSidebarHistoryOpen\(false\);[\s\S]*handleSelectSession\(sessionId\)/);
  assert.match(assistant, /import \{ AssistantSidebarHistoryDropdown \} from '\.\/AIAssistant\/AssistantSidebarHistoryDropdown'/);
  assert.match(assistant, /onSelectSession=\{handleSidebarSelectSession\}/);
  assert.doesNotMatch(assistant, /<AssistantSidebarHistoryDropdown[\s\S]*onNewChat=\{handleSidebarNewChat\}/);
  assert.doesNotMatch(assistant, /sessions\.map\(\(session\) =>/);
  assert.match(sidebarDropdown, /export const AssistantSidebarHistoryDropdown: React\.FC<AssistantSidebarHistoryDropdownProps>/);
  assert.match(sidebarDropdown, /id="assistant-sidebar-history-panel"/);
  assert.match(sidebarDropdown, /inert=\{!isOpen\}/);
  assert.match(sidebarDropdown, /origin-top transition-all duration-200 ease-out/);
  assert.match(sidebarDropdown, /isOpen\s*\?\s*'pointer-events-auto translate-y-0 opacity-100/);
  assert.match(sidebarDropdown, /:\s*'pointer-events-none -translate-y-3 opacity-0/);
  assert.doesNotMatch(sidebarDropdown, /MessageSquarePlus/);
  assert.doesNotMatch(sidebarDropdown, /onNewChat/);
  assert.doesNotMatch(sidebarDropdown, /对话记录<\/div>/);
  assert.doesNotMatch(sidebarDropdown, /AI 助手<\/div>/);
  assert.doesNotMatch(sidebarDropdown, />\s*新建\s*</);
  assert.doesNotMatch(sidebarDropdown, /border-b border-slate-200 px-3 py-3/);
  assert.match(sidebarDropdown, /sessions\.map\(\(session\) =>/);
  assert.match(sidebarDropdown, /const hasPendingDraft = isPendingLatestPreview\(session\)/);
  assert.match(sidebarDropdown, /formatRelativeTime\(session\.updated_at\)/);
  assert.match(sidebarDropdown, /onClick=\{\(\) => onSelectSession\(session\.id\)\}/);
  assert.match(assistant, /surface=\{isSidebarSurface \? 'sidebar' : 'mobile'\}/);
  assert.match(assistant, /hideSelectedResumeCard=\{isSidebarSurface\}/);
  assert.doesNotMatch(assistant, /onSelectResumeExperiences/);
  assert.match(assistant, /hasContextItems=\{composerAttachments\.length > 0 \|\| Boolean\(selectedResume\)\}/);
  assert.match(assistant, /surface=\{isSidebarSurface \? 'sidebar' : 'full'\}/);
  assert.match(assistant, /suggestedFollowups=\{latestSuggestedFollowups\}/);
  assert.match(assistant, /onSelectSuggestedFollowup=\{handleSelectSkillFollowup\}/);
  assert.match(assistant, /placeholder="随心输入"/);
  assert.doesNotMatch(assistant, /selectedExperiences=\{selectedExperiences\}/);
  assert.doesNotMatch(assistant, /key: 'pick-experience'/);
  assert.doesNotMatch(assistant, /label: '选择经历'/);
  assert.match(assistant, /!isSidebarSurface \? \(\s*<AssistantDesktopDraftPanel/);
  assert.match(chatInput, /surface\?: 'full' \| 'sidebar'/);
  assert.match(chatInput, /surface = 'full'/);
  assert.match(chatInput, /const isSidebarSurface = surface === 'sidebar';/);
  assert.match(chatInput, /const textareaMaxHeight = isSidebarSurface \? 112 : 160;/);
  assert.match(chatInput, /Math\.min\(fullHeight, textareaMaxHeight\)/);
  assert.match(chatInput, /fullHeight > textareaMaxHeight \? 'auto' : 'hidden'/);
  assert.match(chatInput, /min-h-\[40px\] max-h-\[112px\][^']*sm:min-h-\[44px\]/);
  assert.match(chatInput, /min-h-\[56px\] max-h-\[160px\][^']*sm:min-h-\[60px\]/);
  assert.match(chatInput, /className=\{textareaClassName\}/);

  assert.match(draftPanel, /surface\?: 'mobile' \| 'sidebar'/);
  assert.match(draftPanel, /surface === 'sidebar' \? 'mb-2' : 'mb-2 md:hidden'/);
  assert.match(draftPanel, /versionState=\{getDraftVersionState\(surface\)\}/);
  assert.match(draftState, /export type DraftSurface = 'desktop' \| 'mobile' \| 'sidebar'/);
  assert.match(draftState, /surface !== 'desktop'/);
});
