"""Hard resource ceilings for export snapshots and rendered PDFs."""

MAX_ACTIVE_EXPORT_SNAPSHOTS_PER_USER = 20
MAX_EXPORT_SNAPSHOT_PAYLOAD_BYTES_PER_USER = 32 * 1024 * 1024
MAX_EXPORT_PERSISTED_BYTES_PER_USER = 64 * 1024 * 1024
MAX_ACTIVE_EXPORT_RENDER_CLAIMS_PER_USER = 2
MAX_CONCURRENT_EXPORT_RENDERS = 4
MAX_RENDERED_PDF_BYTES = 16 * 1024 * 1024
MAX_EXPORT_SNAPSHOT_TOKEN_CHARACTERS = 4096
EXPORT_SNAPSHOT_CLEANUP_INTERVAL_SECONDS = 60
EXPORT_BROWSER_CLEANUP_GRACE_SECONDS = 2.0

MAX_EXPORT_ID_CHARACTERS = 256
MAX_EXPORT_SHORT_TEXT_CHARACTERS = 512
MAX_EXPORT_LONG_TEXT_CHARACTERS = 20_000
MAX_EXPORT_LAYOUT_TOKEN_CHARACTERS = 128
MAX_EXPORT_SECTION_ORDER_ITEMS = 32
MAX_EXPORT_EXPERIENCE_ITEMS = 200
MAX_EXPORT_EDUCATION_ITEMS = 100
MAX_EXPORT_CERTIFICATION_ITEMS = 200
MAX_EXPORT_SKILL_GROUP_ITEMS = 50
MAX_EXPORT_SKILLS_PER_GROUP = 100
MAX_EXPORT_BANK_SKILL_ITEMS = 500
MAX_EXPORT_PROFILE_LINK_ITEMS = 50
MAX_EXPORT_NESTED_COLLECTION_ITEMS = 500
